# Site settings
title: Dr. Anirban Mukherjee 
author:
  name: Anirban Mukherjee
  email: am253@cornell.edu
description: "Homepage of Anirban Mukherjee."

avatar: "/anirban_mukherjee.jpg"

# Build settings
remote_theme: jekyll/minima
